### ISSUE TITLE
Add to the link the automatic length recognition

### ISSUE THREAD

**Issue by mariushosting** [remvze/pswd#2]
Hello remvze! Awesome project as always!
It would be great to add to the web link the automatic length recognition like this:

Like this: https://it-tools.tech/token-generator?length=127

**Comment by remvze** [comment]
Hello there, great suggestion!

You can now set the length of the password using the `length` URL parameter:
```
https://pswd.mvze.net/?length=16
```

You can also set the word count for the passphrase using the `words` URL parameter:
```
https://pswd.mvze.net/?words=8
```

**Comment by mariushosting** [comment]
Amazing!
