### ISSUE TITLE
estimated cracking time wrong

### ISSUE THREAD

**Issue by coro1404** [remvze/pswd#3]
Hi 

Webgui suggests very short cracking times for e.g. 12 character mixed (number, symbols etc.) passwords. Does not match this table 

![image](https://github.com/user-attachments/assets/17ed5528-593c-4f3c-a25c-923f0d26b3a9)

**Comment by remvze** [comment]
Hey there. I tried going for the worst-case scenario, which is offline brute force of fast hashes (e.g., SHA-256), which is much faster than what it takes to brute-force a more secure KDF such as PBKDF2 with high iterations. I can certainly change it, but I much prefer to select my password based on the worst-case scenario.
